### ISSUE TITLE
Date slider jumps around when changing week with arrow keys

### ISSUE THREAD

**Issue by ethanplunkett** [UMassCDS/avianfluapp#27]
If you move the date slider off the current week and then change the week with with the arrow keys it jumps briefly to the current week before landing on the correct week.  For instance if I drag it from 41 (current week) to 26 and then hit the right arrow it jumps briefly to 41 before landing on 27.

**Comment by pmandler-umass** [comment]
Closed with #34 .

**Comment by pmandler-umass** [comment]
Closed with https://github.com/UMassCDS/avianfluapp/issues/34 .
